[package]
name = "main"
type = "bin"
authors = ["slokh"]
compiler_version = ">=0.38.0"
version = "0.1.1"

[dependencies]
merkle_tree = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
lib = { path = "../lib" }
